# Generated by Django 4.1.4 on 2023-10-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerletter_data',
            old_name='name',
            new_name='full_name',
        ),
    ]
